# config file for BCProtect bukkit plugin.

# set true if you want a lot debug messages on the console
debugQuadtree: false
debugRegions: false

# set false to protect the network against grief
canBuild: false

# set to false to prevent pistons moves
enablePistons: false

# set to false to prevent mobs spawn, attack, explode, teleport, etc.
enableMobs: false

# set to false to protect chest, furnaces, hoppers, droppers,etc. against grief/robbery
canOpenInventory: false

# set to false to control player access in the area if they are not in a vehicle
canAccess: false

# set to false if you want to disable creation of vehicle directly in the network
createCart: false

# set to false if you want to disable destruction of vehicle directly in the network
destroyCart: false