# config file for BCProtect bukkit plugin.

# set true if you want a lot debug messages on the console
debugQuadtree: false
debugRegions: false

# set false to protect the network against grief
canbuild: false

# set to false to prevent pistons moves
enablePistons: false

# set to false to prevent mobs spawn, attack, explode, teleport, etc.
enableMobs: false

